services:
  # tailscale:
  #   container_name: tailscale
  #   image: tailscale/tailscale
  #   volumes:
  #     - /mnt/cache/appdata/tailscale/state:/var/lib/tailscale
  #     - /mnt/cache/appdata/tailscale/socket:/var/run/tailscale
  #   environment:
  #     TS_HOSTNAME: in
  #     TS_STATE_DIR: /var/lib/tailscale
  #     TS_AUTH_ONCE: true
  #     TS_USERSPACE: true
  #     TS_SOCKET: /var/run/tailscale/tailscaled.sock
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   labels:
  #     - net.unraid.docker.icon=https://raw.githubusercontent.com/dkaser/unraid-tailscale/main/logo.png
  #   restart: unless-stopped

  traefik:
    container_name: traefik
    image: traefik
    # depends_on:
    #   - tailscale
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - /var/lib/tailscale:/var/lib/tailscale
      # - /var/run/tailscale:/var/run/tailscale
      - /mnt/cache/appdata/traefik/traefik.toml:/etc/traefik.toml:ro
      - /mnt/cache/appdata/certs:/certs
    labels:
      - net.unraid.docker.icon=https://raw.githubusercontent.com/ibracorp/unraid-templates/master/icons/traefik.png
      - net.unraid.docker.webui=http://zero:8080
    healthcheck:
      test: nc -zv 127.0.0.1 443
      interval: 30s
      timeout: 5s
      retries: 3
    command:
      - '--log.level=INFO'
      - '--accesslog=true'
      - '--accesslog.filters.statuscodes=400-499,500-599'
      - '--api.dashboard=true'
      - '--api.insecure=true'
      - '--providers.docker'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.file.filename=/etc/traefik.toml'
      # - '--entryPoints.http.address=:80'
      - '--entryPoints.https.address=:443'
      # - '--certificatesResolvers.mistchicken.tailscale'
      # - '--certificatesresolvers.desec.acme.dnschallenge.disablePropagationCheck=true'
      # - '--certificatesresolvers.desec.acme.dnschallenge=true'
      # - '--certificatesresolvers.desec.acme.dnschallenge.provider=desec'
      # - '--certificatesresolvers.desec.acme.email=crouchingmuppet@icloud.com'
      # - '--certificatesresolvers.desec.acme.storage=/certs/desec.json'
    ports:
      - 8080:8080
      # - 80:80
      - 443:443
    # network_mode: service:tailscale
